Home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index' ),
	url(r'^homevisits/$', views.hvisits, name = 'hvisits' ),
	url(r'^outofhours/$', views.outofhours, name = 'outofhours' ),
	url(r'^chaperones/$', views.chaperones, name = 'chaperones' ),
	url(r'^leaflets/$', views.leaflets, name = 'leaflets' ),
	url(r'^newpatients/$', views.newpatients, name = 'newpatients' ),
	url(r'^vaccines/$', views.vaccines, name = 'vaccines' ),
	url(r'^carers/$', views.carers, name = 'carers' ),
	url(r'^candc/$', views.candc, name = 'candc' ),
	url(r'^equalopps/$', views.equalopps, name = 'equal opps' ),
	url(r'^datapro/$', views.datapro, name = 'datapro' ),
	url(r'^nhscon/$', views.nhscon, name = 'nhs con' ),
]

MyWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Home.urls')),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'^login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^(?P<user_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<user_id>[0-9]+)/update_profile/$', views.update_profile, name='update_profile'),
    url(r'^book/', views.book, name='book'),
    url(r'^view/', views.view, name='view'),
    url(r'^staff/', views.staff, name='staff'),
]

posts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.post_list, name ="list"),
	url(r'^create/$', views.post_create, name="create"),
	url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name = "update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
	url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name = 'detail'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

class Profile(models.Model):
    user = models.ForeignKey(User, default=User)
    Firstname = models.CharField(max_length=250, default='Enter first name name here')
    Surname = models.CharField(max_length=250, default='Enter surname name here')
    first_line_of_address = models.CharField(max_length=250, default='Enter 1st line of address here')
    second_line_of_address = models.CharField(max_length=250, default='Enter 2nd line of address here')
    County = models.CharField(max_length=250, default='Enter your county here')
    City = models.CharField(max_length=250, default='Enter your city here')
    Postcode = models.CharField(max_length=250, default='Enter your postcode here')
    Telephone_number = models.CharField(max_length=250, default='Enter telephone number here')
    profile_pic = models.FileField()
    create = models.BooleanField(default=False)

    def __str__(self):
        return self.Firstname + ' - ' + self.Surname

class Booking(models.Model):
    doctor = models.ForeignKey('Doctor')
    date = models.DateField(auto_now=False, auto_now_add=False)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    name = models.CharField(max_length=30)
    email = models.EmailField('Email', max_length=30)
    Telephone_number = models.CharField(max_length=250)

    class Meta:
        unique_together = ('doctor', 'date', 'start_time',)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


"""
It contains the information about the Hall, i.e. what is the name of the hall and its other hall featured related
informations.
"""


class Doctor(models.Model):
    doctor = models.ForeignKey(User)
    Firstname = models.CharField(max_length=250)
    Surname = models.CharField(max_length=250)
    doctor_admin = models.EmailField(max_length=40)

    class Meta:
        unique_together = ('doctor', 'doctor_admin')

    def __unicode__(self):
        return self.Surname

    def __str__(self):
        return self.Surname

login/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.core.exceptions import ValidationError
from django.db.models import Q
from django import forms
from .models import Booking
from datetime import timedelta
import datetime

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['Firstname', 'Surname', 'profile_pic', 'first_line_of_address',
                  'second_line_of_address', 'County', 'City', 'Postcode',
                  'Telephone_number']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']



"""
This form is used for booking the hall for an event by registered users and the request will be sent to the admin only
if the timing slot is available for booking.
"""


class BookingForm(forms.ModelForm):
    # This connects the 'Booking' model with this form and shows the specified fields on the html.
    class Meta:
        model = Booking
        exclude = ['status', 'email']

    """
    If the input date is not valid then it will show a validation message.
    The form will also raise a validation error if the start time or the end time of the event is between the timings
    for	already booked or hall to be booked. e.g. If the hall is booked from 8AM to 10AM, then the user can't book
    the hall from 9AM to 10AM.
    """

    def clean(self):
        try:
            # Getting form data used for checking whether the booking can be done or not for filled entries.
            form_data = self.cleaned_data
            event_date = form_data['date']
            doc = form_data['doctor']
            event_start = form_data['start_time']
            print(event_start)


            # Getting the current date and time for comparing
            time_now = datetime.datetime.now().strftime('%H:%M:00')
            date_today = datetime.date.today()

            # For converting event_start from datetime.time to datetime.datetime, combine method is used for it and then
            # adding or subtracting number of hours from it.
            e_start = (datetime.datetime.combine(datetime.date.today(), event_start) + datetime.timedelta(minutes=1)) \
                .strftime('%H:%M:00')

            # For checking duration of the event, as it should not be more than 5 hours.

            # For checking event booking date and timings such that no past booking can be done such that for today's
            # date and the start_time as well as end_time should be greater than current time whereas the isoformat is
            # used for converting the time to the string and comparing the value with the form time values
            if (event_date == date_today and (event_start.isoformat() <= time_now)):
                raise forms.ValidationError("Please fill future timings")

            # Comparing the form_data with the values in database for checking already booked hall
            event_time = Booking.objects.filter(Q(start_time__range=(e_start)) | \
                                                Q(start_time__lte=event_start) | \
                                                Q(start_time__gte=event_start),
                                                date=event_date, doctor=doc)

            # If any any booking exists within the entered timgings then the Validation error occurs.
            for t in event_time:
                if t is not None:
                    raise forms.ValidationError("Doctor Already Booked")

            return form_data

        except KeyError:
            print("Please fill the entries")
            # If the exception is raised for KeyError, then the statement will execute till the required entries are filled


"""
This form is used for viewing the future booking in various hall and the user can filter the bookings by selecting the
date and/or the hall such that the list of bookings will be shown.
"""


class ViewBookingsForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['doctor', 'date']

login/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from .forms import UserForm, ProfileForm
from .models import Profile
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.template import RequestContext
from .forms import BookingForm, ViewBookingsForm
from .models import Booking, Doctor
from django.core.mail import EmailMessage
from datetime import timedelta
import datetime


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def staff(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    elif request.user.is_staff and not request.user.is_superuser:
        email = request.user.email
        hall_staff = Doctor.objects.get(doctor_admin=email)
        stf = Booking.objects.filter(Q(date=datetime.date.today(), start_time__gte=datetime.datetime.now(). \
                                       strftime('%I:%M %p')) | Q(date__gt=datetime.date.today()), doctor=hall_staff).order_by(
            '-date', 'start_time')
        return render(request, "reservations/staff.html", {"staff": stf})
    else:
        return HttpResponseRedirect('/')

        

def book(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.user.is_staff or request.user.is_superuser:
        return HttpResponseRedirect('/')
    elif request.user.is_authenticated():
        if request.method == 'POST':
            form = BookingForm(request.POST)
            name = request.POST['name']
            book_doc = request.POST['doctor']

            if form.is_valid():
                value = form.save(commit=False)
                user = User.objects.all()
                value.email = request.user.email
                value.save()

                # Getting hall admin email_id such that the email can be forwarded to the hall_admin.
                email = Doctor.objects.filter(id=book_doc).values('doctor_admin')

                # Sending email to the hall_admin containing event info and user email.
                # user_email = EmailMessage('Booking System', 'Please accept the request for booking', to=[email])
                # user_email.send()
                return render(request, "reservations/thanks.html", {})
        else:
            form = BookingForm()
        return render(request, "reservations/book.html", {"form": form})
    

def view(request):
    if request.method == 'POST':
        form = ViewBookingsForm(request.POST)
        view_doc = request.POST['doctor']
        view_date = request.POST['date']
        if form.is_valid():
            boo = Booking.objects.filter( doctor=view_doc, date=view_date)
            return render(request, "reservations/view_booking.html", {"booking": boo, "view": view, })
    else:
        form = ViewBookingsForm()
    return render(request, "reservations/view.html", {"form": form})


def update_profile(request, user_id):
    instance = get_object_or_404(Profile, pk=user_id)
    form = ProfileForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #messages.success(request, "Changes saved")
        user = request.user
        profile = get_object_or_404(Profile, pk=user_id)
        return render(request, 'login/detail.html', {'profile': profile, 'user': user})
    context = {
		"profile": instance,
		"form":form,
	}
    return render(request, 'login/create_profile.html', context)

def create_profile(request):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.id = profile.user_id
            profile.create = True
            profile.profile_pic = request.FILES['profile_pic']
            file_type = profile.profile_pic.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'profile': profile,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'login/create_profile.html', context)
            profile.save()
            return render(request, 'login/detail.html', {'profile': profile})
        context = {
            "form": form,
        }
        return render(request, 'login/create_profile.html', context)

def detail(request, user_id):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        user = request.user
        profile = get_object_or_404(Profile, pk=user_id)
        return render(request, 'login/detail.html', {'profile': profile, 'user': user})

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        return render(request, 'login/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'login/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'login/index.html')
            else:
                return render(request, 'login/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login/login.html', {'error_message': 'Invalid login'})
    return render(request, 'login/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'login/index.html')
    context = {
        "form": form,
    }
    return render(request, 'login/register.html', context)

login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Welcome {{ user.username }}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}"/>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'login/js/main.js' %}"></script>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <style>
        html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
        .w3-sidenav a,.w3-sidenav h4 {font-weight:bold}
    </style>
</head>

<body class="w3-light-grey w3-content" style="max-width:1600px">

<!-- Sidenav/menu -->
<nav class="w3-sidenav w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidenav"><br>
  <div class="w3-container">
    <a href="#" onclick="w3_close()" class="w3-hide-large w3-right w3-jumbo w3-padding" title="close menu">
      <i class="fa fa-remove"></i>
    </a>
    <img src="{% static 'personal/img/babypic.jpg' %}" style="width:45%; height:75px" class="w3-round"><br><br>
	{% if user.is_superuser %}
		<h4 class="w3-padding-0"><b>SUPERUSER</b></h4>
	{% elif user.is_staff %}
		<h4 class="w3-padding-0"><b>STAFF</b></h4>
	{% else %}
		<h4 class="w3-padding-0"><b>USER</b></h4>
	{% endif %}



  </div>
  <a href="{% url 'login:index' %}" class="w3-padding">Home</a>
  <a href="{% url 'login:detail' user.id %}" class="w3-padding">PROFILE</a>
    {% if user.is_superuser %}
  <a href="{% url 'login:view' %}" class="w3-padding">APPOINTMENTS</a>
    {% elif user.is_staff and not user.is_superuser %}
  <a href="{% url 'login:staff' %}" class="w3-padding">APPOINTMENTS</a>
    {% else %}
  <a href="{% url 'login:book' %}" class="w3-padding">APPOINTMENTS</a>
    {% endif %}
  {% if user.is_superuser or user.is_staff %}
	<a href="{% url 'posts:list' %}" class="w3-padding">FEEDBACK</a>
  {% else %}
    <a href="{% url 'posts:create' %}" class="w3-padding">FEEDBACK</a>
  {% endif %}
  {% if profile.create %}
    <a href="{% url 'login:update_profile' user.id %}" class="w3-padding">UPDATE PROFILE</a>
  {% else %}
    <a href="{% url 'login:create_profile' %}" class="w3-padding">SETTINGS</a>
  {% endif %}

  <a href="{% url 'login:logout_user' %}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> LOGOUT</a>
</nav>

<!-- Overlay effect when opening sidenav on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px">

  <!-- Header -->
<header class="w3-container">
    <a href="#"><img src="img_avatar_g2.jpg" style="width:65px;" class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
    <span class="w3-opennav w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i class="fa fa-bars"></i></span>
    <h1><b>Welcome {{ user.username }}</b></h1>
    <div class="w3-section w3-bottombar w3-padding-16">
    </div>
</header>
        {% block body %}
        {% endblock %}


</div>

<script>
// Script to open and close sidenav
function w3_open() {
    document.getElementById("mySidenav").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}
function w3_close() {
    document.getElementById("mySidenav").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}

function openCity(evt, cityName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
     tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-red";
}
</script>

</body>
</html>

login/templates/login/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Doc site{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'login/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src= "{% static 'personal/img/NHS.jpg' %}" alt ="NHS" style="max-width:65px; max-height:25px; margin-top:0px; margin-left:20px"></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-center">
                    <li><a href="/">HOME</a></li>
                    <li><a href="#">DOCTORS & STAFF</a></li>
                    <li><a href="#">APPOINTMENTS</a></li>
                    <li><a href="#">PRESCRIPTIONS</a></li>
                    <li><a href="#">SERVICES PROVIDED</a></li>
                    <li><a href="#">CONTACT US</a></li>
			  </ul>
			  <ul class = "nav navbar-nav navbar-right">
                  <li class="{% block register_active %}{% endblock %}"><a href="{% url 'login:register' %}"><span class="glyphicon glyphicon-new-window"></span> REGISTER</a></li>
                  <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login:login_user' %}"><span class="glyphicon glyphicon-log-in"></span> LOGIN</a></li>
			  </ul>
            </div>
        </div>
    </nav>

{% block body %}
{% endblock %}

</body>
</html>

login/templates/login/create_profile.html
{% extends 'login/base.html' %}
{% block title %}Create Profile{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Edit profile</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'login/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

login/templates/login/detail.html
{% extends 'login/base.html' %}
{% block title %}{{ profile }}{% endblock %}
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'login:detail' user.id %}">
                        {% if profile.profile_pic %}
                            <img src="{{ profile.profile_pic.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ profile.Firstname }} <small>{{ profile.Surname }}</small></h1>
                    <h2>{{ profile.TelephoneNumber }}</h2>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

login/templates/login/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

login/templates/login/index.html
{% extends 'login/base.html' %}

{% block body %}

	{% if user.is_staff %}
		<h3>STAFF</h3>
	{% elif user.is_superuser %}
		<h3>SUPERUSER</h3>
	{% else %}
		<h3>USER</h3>
	{% endif %}

{% endblock %}

login/templates/login/login.html
{% extends 'login/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid" style="margin-top:100px">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'login:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'login:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

login/templates/login/register.html
{% extends 'login/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid" style="margin-top:100px">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'login/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'login:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

login/templates/login/settings.html
{% extends 'login/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h3> settings</h3>
        </div>
    </div>
</div>
{% endblock %}