Home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index' ),
	url(r'^homevisits/$', views.hvisits, name = 'hvisits' ),
	url(r'^outofhours/$', views.outofhours, name = 'outofhours' ),
	url(r'^chaperones/$', views.chaperones, name = 'chaperones' ),
	url(r'^leaflets/$', views.leaflets, name = 'leaflets' ),
	url(r'^newpatients/$', views.newpatients, name = 'newpatients' ),
	url(r'^vaccines/$', views.vaccines, name = 'vaccines' ),
	url(r'^carers/$', views.carers, name = 'carers' ),
	url(r'^candc/$', views.candc, name = 'candc' ),
	url(r'^equalopps/$', views.equalopps, name = 'equal opps' ),
	url(r'^datapro/$', views.datapro, name = 'datapro' ),
	url(r'^nhscon/$', views.nhscon, name = 'nhs con' ),
]

MyWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Home.urls')),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'^login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^(?P<user_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<user_id>[0-9]+)/update_profile/$', views.update_profile, name='update_profile'),
    url(r'^book/', views.book, name='book'),
    url(r'^view/', views.view, name='view'),
    url(r'^staff/', views.staff, name='staff'),
]

Home/models.py
from django.db import models

class Notices(models.Model):
	title = models.CharField(max_length = 140)	
	body = models.TextField()
		
	def __unicode__(self):
		return self.title
		
	def __str__(self):
		return self.title

login/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

class Profile(models.Model):
    user = models.ForeignKey(User, default=User)
    Firstname = models.CharField(max_length=250, default='Enter first name name here')
    Surname = models.CharField(max_length=250, default='Enter surname name here')
    first_line_of_address = models.CharField(max_length=250, default='Enter 1st line of address here')
    second_line_of_address = models.CharField(max_length=250, default='Enter 2nd line of address here')
    County = models.CharField(max_length=250, default='Enter your county here')
    City = models.CharField(max_length=250, default='Enter your city here')
    Postcode = models.CharField(max_length=250, default='Enter your postcode here')
    Telephone_number = models.CharField(max_length=250, default='Enter telephone number here')
    profile_pic = models.FileField()
    create = models.BooleanField(default=False)

    def __str__(self):
        return self.Firstname + ' - ' + self.Surname

class Booking(models.Model):
    doctor = models.ForeignKey('Doctor')
    date = models.DateField(auto_now=False, auto_now_add=False)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    name = models.CharField(max_length=30)
    email = models.EmailField('Email', max_length=30)
    Telephone_number = models.CharField(max_length=250)

    class Meta:
        unique_together = ('doctor', 'date', 'start_time',)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


"""
It contains the information about the Hall, i.e. what is the name of the hall and its other hall featured related
informations.
"""


class Doctor(models.Model):
    doctor = models.ForeignKey(User)
    Firstname = models.CharField(max_length=250)
    Surname = models.CharField(max_length=250)
    doctor_admin = models.EmailField(max_length=40)

    class Meta:
        unique_together = ('doctor', 'doctor_admin')

    def __unicode__(self):
        return self.Surname

    def __str__(self):
        return self.Surname

login/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.core.exceptions import ValidationError
from django.db.models import Q
from django import forms
from .models import Booking
from datetime import timedelta
import datetime

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['Firstname', 'Surname', 'profile_pic', 'first_line_of_address',
                  'second_line_of_address', 'County', 'City', 'Postcode',
                  'Telephone_number']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']



"""
This form is used for booking the hall for an event by registered users and the request will be sent to the admin only
if the timing slot is available for booking.
"""


class BookingForm(forms.ModelForm):
    # This connects the 'Booking' model with this form and shows the specified fields on the html.
    class Meta:
        model = Booking
        exclude = ['status', 'email']

    """
    If the input date is not valid then it will show a validation message.
    The form will also raise a validation error if the start time or the end time of the event is between the timings
    for	already booked or hall to be booked. e.g. If the hall is booked from 8AM to 10AM, then the user can't book
    the hall from 9AM to 10AM.
    """

    def clean(self):
        try:
            # Getting form data used for checking whether the booking can be done or not for filled entries.
            form_data = self.cleaned_data
            event_date = form_data['date']
            doc = form_data['doctor']
            event_start = form_data['start_time']
            print(event_start)


            # Getting the current date and time for comparing
            time_now = datetime.datetime.now().strftime('%H:%M:00')
            date_today = datetime.date.today()

            # For converting event_start from datetime.time to datetime.datetime, combine method is used for it and then
            # adding or subtracting number of hours from it.
            e_start = (datetime.datetime.combine(datetime.date.today(), event_start) + datetime.timedelta(minutes=1)) \
                .strftime('%H:%M:00')

            # For checking duration of the event, as it should not be more than 5 hours.

            # For checking event booking date and timings such that no past booking can be done such that for today's
            # date and the start_time as well as end_time should be greater than current time whereas the isoformat is
            # used for converting the time to the string and comparing the value with the form time values
            if (event_date == date_today and (event_start.isoformat() <= time_now)):
                raise forms.ValidationError("Please fill future timings")

            # Comparing the form_data with the values in database for checking already booked hall
            event_time = Booking.objects.filter(Q(start_time__range=(e_start)) | \
                                                Q(start_time__lte=event_start) | \
                                                Q(start_time__gte=event_start),
                                                date=event_date, doctor=doc)

            # If any any booking exists within the entered timgings then the Validation error occurs.
            for t in event_time:
                if t is not None:
                    raise forms.ValidationError("Doctor Already Booked")

            return form_data

        except KeyError:
            print("Please fill the entries")
            # If the exception is raised for KeyError, then the statement will execute till the required entries are filled


"""
This form is used for viewing the future booking in various hall and the user can filter the bookings by selecting the
date and/or the hall such that the list of bookings will be shown.
"""


class ViewBookingsForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['doctor', 'date']

Home/views.py
from django.shortcuts import render
from .models import Notices
def index(request):
        model= Notices
        return render(request, 'home/homepage.html')
	
def hvisits(request):
	return render(request, 'home/hvisits.html')

def outofhours(request):
	return render(request, 'home/outofhours.html')
	
def chaperones(request):
	return render(request, 'home/chaperones.html')

def leaflets(request):
	return render(request, 'home/leaflets.html')

def newpatients(request):
	return render(request, 'home/newpatients.html')

def vaccines(request):
	return render(request, 'home/vaccines.html')

def carers(request):
	return render(request, 'home/carers.html')
	
def candc(request):
	return render(request, 'home/candc.html')

def equalopps(request):
	return render(request, 'home/equalopps.html')

def datapro(request):
	return render(request, 'home/datapro.html')
	
def nhscon(request):
	return render(request, 'home/nhscon.html')

login/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from .forms import UserForm, ProfileForm
from .models import Profile
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.template import RequestContext
from .forms import BookingForm, ViewBookingsForm
from .models import Booking, Doctor
from django.core.mail import EmailMessage
from datetime import timedelta
import datetime


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def staff(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    elif request.user.is_staff and not request.user.is_superuser:
        email = request.user.email
        hall_staff = Doctor.objects.get(doctor_admin=email)
        stf = Booking.objects.filter(Q(date=datetime.date.today(), start_time__gte=datetime.datetime.now(). \
                                       strftime('%I:%M %p')) | Q(date__gt=datetime.date.today()), doctor=hall_staff).order_by(
            '-date', 'start_time')
        return render(request, "reservations/staff.html", {"staff": stf})
    else:
        return HttpResponseRedirect('/')

        

def book(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.user.is_staff or request.user.is_superuser:
        return HttpResponseRedirect('/')
    elif request.user.is_authenticated():
        if request.method == 'POST':
            form = BookingForm(request.POST)
            name = request.POST['name']
            book_doc = request.POST['doctor']

            if form.is_valid():
                value = form.save(commit=False)
                user = User.objects.all()
                value.email = request.user.email
                value.save()

                # Getting hall admin email_id such that the email can be forwarded to the hall_admin.
                email = Doctor.objects.filter(id=book_doc).values('doctor_admin')

                # Sending email to the hall_admin containing event info and user email.
                # user_email = EmailMessage('Booking System', 'Please accept the request for booking', to=[email])
                # user_email.send()
                return render(request, "reservations/thanks.html", {})
        else:
            form = BookingForm()
        return render(request, "reservations/book.html", {"form": form})
    

def view(request):
    if request.method == 'POST':
        form = ViewBookingsForm(request.POST)
        view_doc = request.POST['doctor']
        view_date = request.POST['date']
        if form.is_valid():
            boo = Booking.objects.filter( doctor=view_doc, date=view_date)
            return render(request, "reservations/view_booking.html", {"booking": boo, "view": view, })
    else:
        form = ViewBookingsForm()
    return render(request, "reservations/view.html", {"form": form})


def update_profile(request, user_id):
    instance = get_object_or_404(Profile, pk=user_id)
    form = ProfileForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #messages.success(request, "Changes saved")
        user = request.user
        profile = get_object_or_404(Profile, pk=user_id)
        return render(request, 'login/detail.html', {'profile': profile, 'user': user})
    context = {
		"profile": instance,
		"form":form,
	}
    return render(request, 'login/create_profile.html', context)

def create_profile(request):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.id = profile.user_id
            profile.create = True
            profile.profile_pic = request.FILES['profile_pic']
            file_type = profile.profile_pic.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'profile': profile,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'login/create_profile.html', context)
            profile.save()
            return render(request, 'login/detail.html', {'profile': profile})
        context = {
            "form": form,
        }
        return render(request, 'login/create_profile.html', context)

def detail(request, user_id):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        user = request.user
        profile = get_object_or_404(Profile, pk=user_id)
        return render(request, 'login/detail.html', {'profile': profile, 'user': user})

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'login/login.html')
    else:
        return render(request, 'login/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'login/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'login/index.html')
            else:
                return render(request, 'login/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login/login.html', {'error_message': 'Invalid login'})
    return render(request, 'login/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'login/index.html')
    context = {
        "form": form,
    }
    return render(request, 'login/register.html', context)

login/templates/reservations/book.html
{% extends "base.html" %}
{% block title %}Book appointment{% endblock %}
{% load staticfiles %}
{% block extrastyle %}
	<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css" type="text/css">
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.js"></script>

    <script type=text/javascript>
		$(function() {
			$( "#id_date" ).datepicker({
				// changeMonth: true, //this option for allowing user to select month
				// changeYear:  true, //this option for allowing user to select from year range
	            dateFormat: 'yy-mm-dd',
	            minDate: 0,
	            maxDate: "+3M"
			});
		});

	    $(function() {
			$( "#id_doc" ).selectmenu()
			.selectmenu( "menuWidget" )
			.addClass( "overflow" );
			});


		$(function() {
			$( "#id_start_time" ).timepicker({
				'minTime': '8:',
				'maxTime': '11:',
				'timeFormat': 'h:i',
				'step': 10
			});
		})

	</script>
{% endblock %}

{% block content %}
	<div class="block-book container" style="background-color: transparent;">
		<h1>Book appointment</h1>
		<form method="POST" action=""> {% csrf_token %}
			{{ form.as_p }}
			<input type='submit' value='Proceed' class='round-button' />
		</form>
	</div>
{% endblock %}

login/templates/reservations/cancel.html
{% extends "base.html" %}
{% block title %}Cancellation{% endblock %}
{% block content %}
<div class="block-book container" style="background-color: transparent;">
	<h1>Cancel Bookings</h1>
	<br><br>
	
	{% if view %}
	 	<div>
	 		<form method="POST" action="/cancelbooking/" name="cancelform">
	 			{% csrf_token %}

	 			<div class="table-responsive">
					<table  class="table table-striped table-bordered table-condensed table-hover">
					 	<tr>
					 		<th>Sr.</th>
					 		<th>Event Name</th>
							<th>Name</th>
					 		<th>Venue</th>
					 		<th>Date</th>
					 		<th>Start Time</th>
					 		<th>End Time</th>
					 		<th>Status</th>
					 	</tr>
					 	{% for value in cancel %}
					 	<tr>
					 		<td> <input type="radio" name="cancel" id="cancel{{ forloop.counter }}" value="{{ value.id }}" /></td>
					 		<td>{{ value }}</td> 
					 		<td>{{ value.name }}</td>
					 		<td>{{ value.hall }}</td>
					 		<td>{{ value.date }}</td>
					 		<td>{{ value.start_time }}</td>
					 		<td>{{ value.end_time }}</td>
					 		<td>
					 			{% if value.status %}
					 				Booked
					 			{% else %}
					 				Waiting
					 			{% endif %}
					 		</td>
						</tr>
						{% endfor %}
					</table>
				</div>
				<br><br>

				<input type="submit" value="Cancel Booking" class='round-button' />
			</form>
	 	</div>
	{% else %}
		<h4>No Bookings available for cancellation.</h4>
	{% endif %}
</div>
{% endblock %}

login/templates/reservations/feedback.html
{% extends "base.html" %}
{% block title %}Feedback{% endblock %}
{% block content %}
	<div class="block-book container" style="background-color: transparent;"><br>
		<h1>Your feedback has been submitted</h1>
		
	</div>
{% endblock %}

login/templates/reservations/home.html
{% extends "base.html" %}
{% block title %}Booking System{% endblock %}
{% block content %}
<div class="block-home">
	<h1 class="header hcontent"> Welcome to Booking System</h1>
	<p class="tagline hcontent"> Everything is getting online... but still booking halls manually??? Here is the solution.
	</p>

	<p>
		<div class="buttons">
			<a href="{% url 'view' %}" class="round-btn-view">View Bookings</a>
			<a href="{% url 'book' %}" class="round-btn-book">Book Hall</a>
			<a href="{% url 'cancel' %}" class="round-btn-cancel">Cancellation</a>
			<a href="{% url 'reschedule' %}" class="round-btn-reschedule">Reschedule</a>
		</div>
	</p>
</div>
{% endblock %}

login/templates/reservations/reschedule.html
{% extends "base.html" %}
{% block title %}Event Reschedule{% endblock %}
{% block content %}
	<div class="block-book container" style="background-color: transparent;">
		<h1 class="centralize">Event Reschedule</h1>
		
	</div>
{% endblock %}

login/templates/reservations/staff.html
{% extends "base.html" %}
{% block title %}Staff{% endblock %}
{% block content %}
	<div class="block-book container" style="background-color: transparent;">
		<h1>Staff</h1>
		<br><br>
	 	<div>
	 		<form method="POST" action="/staffresponse/" name="staffform">
	 			{% csrf_token %}
				<table border="2" align="center">
				 	<tr>
				 		<th>Book Event</th>
				 		<th>Cancel Event</th>
				 		<th>Name</th>
				 		<th>Event Name</th>
				 		<th>Venue</th>
				 		<th>Date</th>
				 		<th>Start Time</th>
				 		<th>End Time</th>
				 		<th>Booking Status</th>
				 	</tr>
				 	{% for value in staff %}
				 	<tr>
				 		<td> <input type="radio" name="book" id="book{{ forloop.counter }}" value="{{ value.id }}" /></td>
				 		<td> <input type="radio" name="cancel" id="cancel{{ forloop.counter }}" value="{{ value.id }}" /></td>
				 		<td>{{ value }}</td> 
				 		<td>{{ value.name }}</td>
				 		<td>{{ value.hall }}</td>
				 		<td>{{ value.date }}</td>
				 		<td>{{ value.start_time }}</td>
				 		<td>{{ value.end_time }}</td>
				 		<td>{{ value.status }}</td>
					</tr>
					{% endfor %}
				</table>
				<br><br>
				<input type="submit" value="Update Bookings" class='round-button' />
				<input type="reset" value="Reset" class='round-btn-cancel' />
			</form>
	 	</div>
	</div>
{% endblock %}

login/templates/reservations/thanks.html
{% extends "base.html" %}
{% block title %}Thanks for Booking{% endblock %}
{% block content %}
	<div class="block-book container" style="background-color: transparent;">
		<h4 class="centralize">Thanks for Booking :)</h4>
		<p class="centralize">You will receive a confirmation email from us.</p>
	</div>
{% endblock %}

login/templates/reservations/view.html
{% extends "base.html" %}
{% block title %}View Bookings{% endblock %}
{% load staticfiles %}
{% block extrastyle %}
	<!-- <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css" type="text/css">
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.js"></script>
 -->
    <script type=text/javascript>
		$(function() {
			$( "#id_date" ).datepicker({
	            dateFormat: 'yy-mm-dd',
	            minDate: 0,
	            maxDate: "+3M"
			});
		});

	    $(function() {
			$( "#id_hall" ).selectmenu()
			.selectmenu( "menuWidget" )
			.addClass( "overflow" );
			});

	</script>
{% endblock %}

{% block content %}
	<div class="block-book container" style="background-color: transparent;">
		<h1>View Bookings</h1><br><br>
		<form method="POST" action="">
			{% csrf_token %}
			{{ form.as_p }}
			<input type='submit' value='View Bookings' class='round-button' />
		</form>
 	</div>
{% endblock %}

login/templates/reservations/view_booking.html
{% extends "base.html" %}
{% block title %}List of Bookings{% endblock %}
{% block content %}
<div class="block-book container" style="background-color: transparent;">
	<h1>Current Bookings</h1><br><br>
	
	 	<div class="table-responsive">
			<table  class="table table-striped table-bordered table-condensed table-hover">
			 	<tr>
			 		<th>Sr.</th>
			 		<th>Event Name</th>
			 		<th>Organizer Name</th>
			 		<th>Email ID</th>
			 		<th>Venue</th>
			 		<th>Date</th>
			 		<th>Start Time</th>
			 		<th>End Time</th>
			 	</tr> 
		 		{% for value in booking %}
			 	<tr>
			 		<td>{{ forloop.counter }}</td>
			 		<td>{{ value }}</td> 
			 		<td>{{ value.name }}</td>
			 		<td>{{ value.email }}</td>
			 		<td>{{ value.hall }}</td>
			 		<td>{{ value.date }}</td>
			 		<td>{{ value.start_time }}</td>
			 		<td>{{ value.end_time }}</td>
				</tr>
				{% endfor %}
			</table>
	 	</div>
	
</div>
{% endblock %}